# This file generated by GenerateAutoSpider
from dax import AutoSpider

name = 'MP2RAGE'

version = '1.0.0'

exe_lang = 'matlab'

inputs = [
    ("code_path", "PATH", "Path to this code in the repo"),
    ("matlab_bin", "PATH", "Matlab executable"),
    ("nii_dir", "FILE", "NIFTI resource of the MP2RAGE scan"),
    ("project", "STRING", "project"),
    ("subject", "STRING", "subject"),
    ("session", "STRING", "session"),
    ("scan", "STRING", "scan")]

outputs = [
    ("mp2rage.pdf", "FILE", "PDF"),
    ("mp2rage.nii.gz", "FILE", "MP2RAGE")
]

code = r"""%MATLAB
addpath(genpath('${code_path}'))
mp2rage( ...
	'${nii_dir}', ...
	'${temp_dir}', ...
	'${project}', ...
	'${subject}', ...
	'${session}', ...
	'${scan}' ...
	);
"""

if __name__ == '__main__':
    spider = AutoSpider(
        name,
        inputs,
        outputs,
        code,
        version=version,
        exe_lang=exe_lang,
    )

    spider.go()
